#!/bin/python
import python_weather
import asyncio
import sys

class Color:
    RESET       = "\033[0m"

    BLACK       = "\033[30m"
    RED         = "\033[31m"
    GREEN       = "\033[32m"
    YELLOW      = "\033[33m"
    BLUE        = "\033[34m"
    MAGENTA     = "\033[35m"
    CYAN        = "\033[36m"
    WHITE       = "\033[37m"

    BRIGHT_BLACK   = "\033[90m"
    BRIGHT_RED     = "\033[91m"
    BRIGHT_GREEN   = "\033[92m"
    BRIGHT_YELLOW  = "\033[93m"
    BRIGHT_BLUE    = "\033[94m"
    BRIGHT_MAGENTA = "\033[95m"
    BRIGHT_CYAN    = "\033[96m"
    BRIGHT_WHITE   = "\033[97m"

    BG_BLACK     = "\033[40m"
    BG_RED       = "\033[41m"
    BG_GREEN     = "\033[42m"
    BG_YELLOW    = "\033[43m"
    BG_BLUE      = "\033[44m"
    BG_MAGENTA   = "\033[45m"
    BG_CYAN      = "\033[46m"
    BG_WHITE     = "\033[47m"

    BG_BRIGHT_BLACK   = "\033[100m"
    BG_BRIGHT_RED     = "\033[101m"
    BG_BRIGHT_GREEN   = "\033[102m"
    BG_BRIGHT_YELLOW  = "\033[103m"
    BG_BRIGHT_BLUE    = "\033[104m"
    BG_BRIGHT_MAGENTA = "\033[105m"
    BG_BRIGHT_CYAN    = "\033[106m"
    BG_BRIGHT_WHITE   = "\033[107m"

    BOLD       = "\033[1m"
    DIM        = "\033[2m"
    ITALIC     = "\033[3m"
    UNDERLINE  = "\033[4m"
    BLINK      = "\033[5m"
    REVERSE    = "\033[7m"
    HIDDEN     = "\033[8m"
    STRIKETHROUGH = "\033[9m"

async def getWeather(location) -> None:
    async with python_weather.Client(unit=python_weather.IMPERIAL) as client:
        weather = await client.get(str(location))

        print("")
        print(f"{Color.BOLD}Weather for " + str(weather.location) + " at " + str(weather.datetime) + ":")
        print(f"{Color.RESET}{Color.BLUE}It's " + str(weather.kind))
        print(f{Color.RESET}"")
        print(f"Temperature: " + str(weather.temperature) + "Degrees Fahrenheit | " + "Feels Like: " + str(weather.feels_like) + "Degrees Fahrenheit")
        print(f"Precipitation: " + str(weather.precipitation))
        print(f"Wind Speed and Direction: " + str(weather.wind_speed) + "mph | " + str(weather.wind_direction))
        print(f"Humidity: " + str(weather.humidity) + "%")
        print(f"Air Pressure" + str(weather.pressure))
        print(f"Visibility: " + str(weather.visibility))
        print(f"")
        print(str(weather.description))
        print(f{Color.BOLD}{Color.BLUE}"")
        print(f"Daily forecast:{Color.RESET}{Color.YELLOW}")
        print(str(weather.daily_forecasts))
        print(f"{Color.RESET}")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("""Error: Please provide a location.
        Example: termiweather 'New York'""")
        sys.exit(1)
    
    location = sys.argv[1]
    asyncio.run(getWeather(location))
