#!/bin/python
import python_weather
import asyncio
import sys

async def getWeather(location) -> None:
    async with python_weather.Client(unit=python_weather.IMPERIAL) as client:
        weather = await client.get(str(location))

        print("")
        print("Weather for " + str(weather.location) + " at " + str(weather.datetime))
        print("It's " + str(weather.kind))
        print("")
        print("Temperature: " + str(weather.temperature) + "Degrees Fahrenheit | " + "Feels Like: " + str(weather.feels_like) + "Degrees Fahrenheit")
        print("Precipitation: " + str(weather.precipitation))
        print("Wind Speed and Direction: " + str(weather.wind_speed) + "mph | " + str(weather.wind_direction))
        print("Humidity: " + str(weather.humidity) + "%")
        print("Air Pressure" + str(weather.pressure))
        print("Visibility: " + str(weather.visibility))
        print("")
        print(str(weather.description))
        print("")
        print("Daily forecast:")
        print(str(weather.daily_forecasts))
        print("")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("""Error: Please provide a location.
        Example: termiweather 'New York'""")
        sys.exit(1)
    
    location = sys.argv[1]
    asyncio.run(getWeather(location))
